version: "3.2"

services:
  api:
    build: ./images/api
    container_name: api
    ports:
      - 80:3000
    volumes:
    - ./images/api/src:/usr/app/src
    environment:
      PG_CONNECTION_STRING: "postgres://user:password@store:5432/testDB"
    depends_on:
      store:
        condition: service_healthy
    command: ["npm","run","prep"]
    # overwrites dockerfile command
  
  store:
    image: postgres:latest
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testDB
      POSTGRES_HOST_AUTH_METHOD: 
    volumes:
      - ./_backup/test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d testDB"]
      interval: 5s
      timeout: 5s
      retries: 10
        