name: testflow

on:
  pull_request:
    branches: [ main, Develop ] 

env: 
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test
  POSTGRES_DB: test
  
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build docker containers
        run: docker-compose -f docker-compose.ci.yml build 

      - name: run docker containers
        run:  docker-compose -f docker-compose.ci. up --exit-code-from api
